- name: Hoorah
  hosts: localhost
  tasks:
    - name: Create EC2 Instance. 
      ec2:
        region: us-east-2
        instance_type: t2.micro
        image: ami-026dea5602e368e96
        wait: yes
        group_id: sg-a7e761dc
        vpc_subnet_id: subnet-4e026402
        aws_access_key: "{{ AWS_EC2_CREATE_ID }}"
        aws_secret_key: "{{ AWS_EC2_CREATE_KEY }}"
      #command: >
      #  aws ec2 run-instances
      #      --image-id ami-026dea5602e368e96
      #      --count 1
      #      --instance-type t2.micro
      #      --security-group-ids sg-a7e761dc
      #      --subnet-id subnet-4e026402